language: python

sudo: false

python:
- "3.9"
- "3.10"
- "3.11"
- "3.12"
- "3.13"

env:
  - DJANGO=4.2
  - DJANGO=5.0
  - DJANGO=5.1
  - DJANGO=master

matrix:
  exclude:
    - python: "3.9"
      env: DJANGO=5.0
    - python: "3.9"
      env: DJANGO=5.1
    - python: "3.9"
      env: DJANGO=master
  include:
    - python: "3.13"
      env: TOXENV=flake8
  allow_failures:
    - env: DJANGO=master

install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
